#!/bin/sh

. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/X11"
ERRFILE="${XDG_CACHE_HOME:-$HOME/.cache}/X11/xsession-errors"

# shellcheck source=$HOME/.xprofile
[ -f ~/.xprofile ] && . "${HOME}"/.xprofile

exec awesome
